[2025-09-02T03:00:01.289+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-09-02T03:00:01.429+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dbt_run_models.run_dbt_models scheduled__2025-09-02T00:00:00+00:00 [queued]>
[2025-09-02T03:00:01.505+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dbt_run_models.run_dbt_models scheduled__2025-09-02T00:00:00+00:00 [queued]>
[2025-09-02T03:00:01.505+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2025-09-02T03:00:01.560+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): run_dbt_models> on 2025-09-02 00:00:00+00:00
[2025-09-02T03:00:01.573+0000] {warnings.py:112} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:62: DeprecationWarning: This process (pid=2752) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-09-02T03:00:01.574+0000] {standard_task_runner.py:64} INFO - Started process 2753 to run task
[2025-09-02T03:00:01.572+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'dbt_run_models', 'run_dbt_models', 'scheduled__2025-09-02T00:00:00+00:00', '--job-id', '895', '--raw', '--subdir', 'DAGS_FOLDER/dbt_dag.py', '--cfg-path', '/tmp/tmpibsoun3o']
[2025-09-02T03:00:01.581+0000] {standard_task_runner.py:91} INFO - Job 895: Subtask run_dbt_models
[2025-09-02T03:00:01.634+0000] {warnings.py:112} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:195: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2025-09-02T03:00:01.734+0000] {task_command.py:426} INFO - Running <TaskInstance: dbt_run_models.run_dbt_models scheduled__2025-09-02T00:00:00+00:00 [running]> on host b5ea13053d47
[2025-09-02T03:00:02.033+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='dbt_run_models' AIRFLOW_CTX_TASK_ID='run_dbt_models' AIRFLOW_CTX_EXECUTION_DATE='2025-09-02T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-09-02T00:00:00+00:00'
[2025-09-02T03:00:02.035+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-09-02T03:00:02.115+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-09-02T03:00:02.119+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', '\n        cd /usr/app &&         dbt run --profiles-dir /usr/app\n        ']
[2025-09-02T03:00:02.147+0000] {subprocess.py:86} INFO - Output:
[2025-09-02T03:00:07.005+0000] {subprocess.py:93} INFO - [0m03:00:07  Running with dbt=1.7.9
[2025-09-02T03:00:07.805+0000] {subprocess.py:93} INFO - [0m03:00:07  Registered adapter: postgres=1.7.9
[2025-09-02T03:00:07.995+0000] {subprocess.py:93} INFO - [0m03:00:07  [[33mWARNING[0m]: Configuration paths exist in your dbt_project.yml file which do not apply to any resources.
[2025-09-02T03:00:07.996+0000] {subprocess.py:93} INFO - There are 1 unused configuration paths:
[2025-09-02T03:00:07.997+0000] {subprocess.py:93} INFO - - models.my_project.sources
[2025-09-02T03:00:08.038+0000] {subprocess.py:93} INFO - [0m03:00:08  Found 3 models, 7 sources, 0 exposures, 0 metrics, 401 macros, 0 groups, 0 semantic models
[2025-09-02T03:00:08.041+0000] {subprocess.py:93} INFO - [0m03:00:08
[2025-09-02T03:00:08.268+0000] {subprocess.py:93} INFO - [0m03:00:08  Concurrency: 4 threads (target='dev')
[2025-09-02T03:00:08.269+0000] {subprocess.py:93} INFO - [0m03:00:08
[2025-09-02T03:00:08.288+0000] {subprocess.py:93} INFO - [0m03:00:08  1 of 3 START sql view model analytics.stg_order_details ........................ [RUN]
[2025-09-02T03:00:08.289+0000] {subprocess.py:93} INFO - [0m03:00:08  2 of 3 START sql view model analytics.stg_orders ............................... [RUN]
[2025-09-02T03:00:08.557+0000] {subprocess.py:93} INFO - [0m03:00:08  2 of 3 OK created sql view model analytics.stg_orders .......................... [[32mCREATE VIEW[0m in 0.26s]
[2025-09-02T03:00:08.563+0000] {subprocess.py:93} INFO - [0m03:00:08  1 of 3 OK created sql view model analytics.stg_order_details ................... [[32mCREATE VIEW[0m in 0.27s]
[2025-09-02T03:00:08.576+0000] {subprocess.py:93} INFO - [0m03:00:08  3 of 3 START sql table model analytics.orders_summary .......................... [RUN]
[2025-09-02T03:00:08.794+0000] {subprocess.py:93} INFO - [0m03:00:08  3 of 3 OK created sql table model analytics.orders_summary ..................... [[32mSELECT 10000[0m in 0.22s]
[2025-09-02T03:00:08.840+0000] {subprocess.py:93} INFO - [0m03:00:08
[2025-09-02T03:00:08.843+0000] {subprocess.py:93} INFO - [0m03:00:08  Finished running 2 view models, 1 table model in 0 hours 0 minutes and 0.80 seconds (0.80s).
[2025-09-02T03:00:08.880+0000] {subprocess.py:93} INFO - [0m03:00:08
[2025-09-02T03:00:08.883+0000] {subprocess.py:93} INFO - [0m03:00:08  [32mCompleted successfully[0m
[2025-09-02T03:00:08.885+0000] {subprocess.py:93} INFO - [0m03:00:08
[2025-09-02T03:00:08.885+0000] {subprocess.py:93} INFO - [0m03:00:08  Done. PASS=3 WARN=0 ERROR=0 SKIP=0 TOTAL=3
[2025-09-02T03:00:10.052+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2025-09-02T03:00:10.053+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-09-02T03:00:10.089+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=dbt_run_models, task_id=run_dbt_models, run_id=scheduled__2025-09-02T00:00:00+00:00, execution_date=20250902T000000, start_date=20250902T030001, end_date=20250902T030010
[2025-09-02T03:00:10.118+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2025-09-02T03:00:10.128+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
